spring:
  datasource:
    url: jdbc:postgresql://db:5432/shopsystem
    username: test
    driver-class-name: org.postgresql.Driver
    password: test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/shopsystem
    username: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false




