version: '2'
services:
  db:
    image: postgres:9.3
    ports:
    - "5000:5432"
    environment:
      - POSTGRES_DB=shopsystem
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  shop-system:
    image: shop-system
    depends_on:
        - db
    ports:
      - 8080:8080
    networks:
      - app
    restart: always
volumes:
  psql_data:
networks:
  app:
